export { ReactComponent as Logo } from 'src/assets/icons/logo.svg'

export { ReactComponent as BellIcon } from 'src/assets/icons/ic-bell.svg'
// export { ReactComponent as BookmarkFilledIcon} from 'src/assets/icons/ic-bookmark-filled.svg'
export { ReactComponent as BookmarkIcon } from 'src/assets/icons/ic-bookmark.svg'
export { ReactComponent as CartIcon } from 'src/assets/icons/ic-cart.svg'
// export { ReactComponent as CheckIcon} from 'src/assets/icons/ic-check.svg'
export { ReactComponent as ChevronIcon } from 'src/assets/icons/ic-chevron.svg'
// export { ReactComponent as CloseIcon} from 'src/assets/icons/ic-close.svg'
export { ReactComponent as CommunityIcon } from 'src/assets/icons/ic-community.svg'
export { ReactComponent as ExpertIcon } from 'src/assets/icons/ic-expert.svg'
// export { ReactComponent as LockIcon} from 'src/assets/icons/ic-lock.svg'
export { ReactComponent as MenuIcon } from 'src/assets/icons/ic-menu.svg'
// export { ReactComponent as NewIcon} from 'src/assets/icons/ic-new.svg'
export { ReactComponent as SearchIcon } from 'src/assets/icons/ic-search.svg'
// export { ReactComponent as StarIcon} from 'src/assets/icons/ic-star.svg'
export { ReactComponent as StoreIcon } from 'src/assets/icons/ic-store.svg'
